# Generated by Django 5.2.5 on 2025-08-31 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='project',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL),
        ),
    ]
